### ISSUE TITLE
what was the original git clone command?

### ISSUE THREAD

**Issue by dcam2015** [githubteacher/merge-conflicts#5]
I was trying to follow along but couldn't get the other branches to appear - I thought it was a standard git clone ..

**Comment by glennon** [comment]
In the class, I think the instructor had a branch called something like: better-remote. He had already made a local copy. Here's how you could make a local copy from the remote repository.

git checkout -b better-remote origin/better-remote

**Comment by glennon** [comment]
You can also see the various remote branches with:

git branch --all

**Comment by dcam2015** [comment]
Thanks!   I'll see if I can try follow the notes with the updated repo

**Comment by patrickmckenna** [comment]
@dcam2015 Sorry for the confusion. @glennon gave you exactly the right solution -- thanks! (This is part of the reason we use Issues.)

Incidentally, Git does offer a shortcut syntax. Assuming `origin/branch-name` exists on your machine,  `git checkout branch-name` is equivalent to `git checkout -b branch-name origin/branch-name`.

**Comment by Khillasaurus** [comment]
Fellow student here:
I recreated what I believe occurred for @dcam2015 

When I used the command "git branch" that was used during class, the teacher had all the branches show up, but only the following showed up for me (using Git Bash on a windows computer). This was because I only requested showing local branches, and not remotes as well. Using @glennon 's solution, the following correct result can be seen:

![first class issue 5 - answering question](https://cloud.githubusercontent.com/assets/11276421/8965181/0dbdee2e-35e7-11e5-9af6-0b2c18c6ff6b.png)

**Comment by dcam2015** [comment]
Thanks @Khillasaurus, this definitely helps see how this happened.
